#!/bin/sh
# Runs ON THE MAC. Branch and working tree for a checkout, with tracked changes
# split into build residue and real edits.
#
# `git status --short` is a flat list, and a flat list is why a branch switch on
# 12 Aug 2026 stopped dead and had to be untangled by hand: two of the modified
# files were lock files that the session's own builds had regenerated, and
# nothing said so. They are tracked, so `git checkout <branch>` refuses to move
# until they are dealt with, and they look exactly like work someone did.
#
# This names them and prints the command, and does NOT run it. A Podfile.lock
# change can be a genuine dependency update; only whoever made the change knows
# which it was.
set -u

# Regenerated by a build, in a Flutter/iOS project, and tracked in most of them.
_gs_residue() {
  case $1 in
    pubspec.lock|*/pubspec.lock) return 0 ;;
    Podfile.lock|*/Podfile.lock) return 0 ;;
    */Flutter/Generated.xcconfig) return 0 ;;
    */Flutter/flutter_export_environment.sh) return 0 ;;
    .flutter-plugins|.flutter-plugins-dependencies) return 0 ;;
  esac
  return 1
}

gitstate() {  # gitstate <repo>
  _r=$1
  [ -n "$_r" ] || { echo '(REPO not set — no checkout on the Mac to report on)'; return 0; }
  [ -d "$_r/.git" ] || { echo "(not a git checkout: $_r)"; return 0; }
  echo "branch     $(git -C "$_r" rev-parse --abbrev-ref HEAD 2>/dev/null)"

  _res=; _chg=; _unt=0
  # The loop variable is _p, NOT path: the Mac's login shell is zsh, where `path`
  # is tied to PATH, and reading a filename into it empties PATH for everything
  # that runs afterwards. It took out `tail` and `appcheck` in the next section
  # of preflight before the name was changed.
  #
  # -z would be safer against odd filenames and is not worth the read loop here;
  # a path with a newline in it would already have broken git status --short.
  git -C "$_r" status --porcelain 2>/dev/null | {
    while read -r st _p; do
      case $st in
        '??') _unt=$((_unt + 1)); continue ;;
      esac
      if _gs_residue "$_p"; then _res="$_res $_p"; else _chg="$_chg $_p"; fi
    done
    if [ -z "$_res" ] && [ -z "$_chg" ] && [ "$_unt" = 0 ]; then
      echo "tree       clean"
    else
      [ -n "$_chg" ] && { echo "changed   $_chg"; }
      [ -n "$_res" ] && {
        echo "residue   $_res"
        echo "           regenerated by any build, and tracked, so a branch switch"
        echo "           stops on them. Discard when they are not a real change:"
        echo "             git -C $_r checkout --$_res"
      }
      [ "$_unt" != 0 ] && echo "untracked  $_unt file(s) — these do not block a branch switch"
    fi
  }
}
