#!/bin/sh
# Runs ON THE MAC. Branch and working tree for a checkout, with tracked changes
# split into build residue and real edits.
#
# `git status --short` is a flat list, and a flat list is why a branch switch on
# 12 Aug 2026 stopped dead and had to be untangled by hand: two of the modified
# files were lock files that the session's own builds had regenerated, and
# nothing said so. They are tracked, so `git checkout <branch>` refuses to move
# until they are dealt with, and they look exactly like work someone did.
#
# This names them and prints the command, and does NOT run it. A Podfile.lock
# change can be a genuine dependency update; only whoever made the change knows
# which it was.
set -u

# Which tracked paths a build regenerates. One glob per line.
#
# This is the framework's answer, not this script's — a React Native checkout
# regenerates Podfile.lock and yarn.lock, a Gradle one regenerates neither. The
# list is a parameter so that `runners/<name>/framework.sh residue` can supply
# it (BACKLOG item 87, runners/README.md call site 1); until that is wired the
# default below is the Flutter/iOS one this script has always used, and nothing
# passes anything else.
: "${RESIDUE_GLOBS:=pubspec.lock
*/pubspec.lock
Podfile.lock
*/Podfile.lock
*/Flutter/Generated.xcconfig
*/Flutter/flutter_export_environment.sh
.flutter-plugins
.flutter-plugins-dependencies}"

# RUN THIS FILE WITH sh. DO NOT SOURCE IT INTO THE SHELL ssh GIVES YOU.
#
# The Mac's login shell is zsh, and zsh is not a POSIX shell in two ways that
# both bite exactly here:
#
#   `for g in $RESIDUE_GLOBS` does not split — zsh leaves an unquoted expansion
#     as one word, so the whole list arrived as a single pattern and matched
#     nothing. Every lock file was then reported as somebody's work, which is
#     precisely the flat list this check exists to undo.
#   `case $p in $g)` does not glob — zsh treats an unquoted variable in a case
#     pattern as a literal string, so `*/Podfile.lock` matched only a file
#     actually called `*/Podfile.lock`. Fixing the splitting alone left this,
#     and `pubspec.lock` passed while `ios/Podfile.lock` did not.
#
# Both passed every test on Linux, where /bin/sh splits and globs, and only a
# live preflight showed either. So preflight executes this with `sh --run`
# rather than sourcing it, and zsh is out of the path. The tests still source it
# and call the function directly, which is why both entry points exist.
#
# This is the third time zsh has cost this file: see the `_p` loop variable
# below, renamed because zsh ties `path` to PATH.
#
# The loop reads lines rather than splitting words anyway, because that is
# correct in both shells and needs no `set -f` to stop `*/pubspec.lock` being
# expanded against the current directory before it is ever compared.
_gs_residue() {
  _gsr=1
  while IFS= read -r _gsg; do
    [ -n "$_gsg" ] || continue
    # shellcheck disable=SC2254
    case $1 in $_gsg) _gsr=0; break ;; esac
  done <<GLOBS
$RESIDUE_GLOBS
GLOBS
  return $_gsr
}

gitstate() {  # gitstate <repo>
  _r=$1
  [ -n "$_r" ] || { echo '(REPO not set — no checkout on the Mac to report on)'; return 0; }
  [ -d "$_r/.git" ] || { echo "(not a git checkout: $_r)"; return 0; }
  echo "branch     $(git -C "$_r" rev-parse --abbrev-ref HEAD 2>/dev/null)"

  _res=; _chg=; _unt=0
  # The loop variable is _p, NOT path: the Mac's login shell is zsh, where `path`
  # is tied to PATH, and reading a filename into it empties PATH for everything
  # that runs afterwards. It took out `tail` and `appcheck` in the next section
  # of preflight before the name was changed.
  #
  # -z would be safer against odd filenames and is not worth the read loop here;
  # a path with a newline in it would already have broken git status --short.
  git -C "$_r" status --porcelain 2>/dev/null | {
    while read -r st _p; do
      case $st in
        '??') _unt=$((_unt + 1)); continue ;;
      esac
      if _gs_residue "$_p"; then _res="$_res $_p"; else _chg="$_chg $_p"; fi
    done
    if [ -z "$_res" ] && [ -z "$_chg" ] && [ "$_unt" = 0 ]; then
      echo "tree       clean"
    else
      [ -n "$_chg" ] && { echo "changed   $_chg"; }
      [ -n "$_res" ] && {
        echo "residue   $_res"
        echo "           regenerated by any build, and tracked, so a branch switch"
        echo "           stops on them. Discard when they are not a real change:"
        echo "             git -C $_r checkout --$_res"
      }
      [ "$_unt" != 0 ] && echo "untracked  $_unt file(s) — these do not block a branch switch"
    fi
  }
}

# Executed rather than sourced: `sh gitstate.sh --run <repo>`. An explicit
# sentinel, because a sourced file sees the sourcing script's $1 and there is no
# $BASH_SOURCE in POSIX sh to tell the two apart.
if [ "${1:-}" = --run ]; then
  gitstate "${2:-}"
fi
